version: '3'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
  worker:
    build: .
    command: celery -A recipe_backend worker -l info
    depends_on:
      - rabbit
    volumes:
      - .:/code
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "/code/wait-for-postgres.sh db
             && python /code/manage.py makemigrations && python /code/manage.py migrate
             && python /code/manage.py loaddata ingredients.json recipes.json recipe_ingredient.json
             && python /code/manage.py populate
             && python /code/manage.py runserver 0.0.0.0:8000"
    container_name: "recipes_api"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
      - rabbit